import type { SdModelPreset } from "../types";
import { diffusionVaeLlmPathInputs } from "./shared";

export const flux2Presets = {
    "flux2-dev": {
        id: "flux2-dev",
        family: "flux2",
        label: "Flux.2 Dev",
        description: "FLUX.2-dev image editing/generation preset with Mistral Small 3.2 LLM encoder.",
        defaultVramProfile: "balanced",
        runMode: "img_gen",
        paths: {},
        pathInputs: diffusionVaeLlmPathInputs,
        defaults: {
            cfgScale: 1,
            samplingMethod: "euler",
            diffusionFa: true,
            offloadToCpu: true,
        },
        supportsRefImage: true,
        downloads: [
            { label: "FLUX.2-dev GGUF", url: "https://huggingface.co/city96/FLUX.2-dev-gguf/tree/main", format: "gguf" },
            { label: "FLUX.2-dev VAE", url: "https://huggingface.co/black-forest-labs/FLUX.2-dev/tree/main", format: "safetensors" },
            { label: "FLUX.2 small decoder", url: "https://huggingface.co/black-forest-labs/FLUX.2-small-decoder/tree/main", format: "safetensors" },
            { label: "Mistral Small 3.2 GGUF", url: "https://huggingface.co/unsloth/Mistral-Small-3.2-24B-Instruct-2506-GGUF/tree/main", format: "gguf" },
        ],
    },
    "flux2-klein-4b": {
        id: "flux2-klein-4b",
        family: "flux2",
        label: "Flux.2 Klein 4B",
        description: "Fast FLUX.2 Klein 4B preset using the Qwen3 4B encoder.",
        defaultVramProfile: "balanced",
        runMode: "img_gen",
        paths: {},
        pathInputs: diffusionVaeLlmPathInputs,
        defaults: {
            cfgScale: 1,
            steps: 4,
            samplingMethod: "euler",
            diffusionFa: true,
            offloadToCpu: true,
        },
        supportsRefImage: true,
        downloads: [
            { label: "FLUX.2 Klein 4B", url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-4B", format: "safetensors" },
            { label: "FLUX.2 Klein 4B GGUF", url: "https://huggingface.co/leejet/FLUX.2-klein-4B-GGUF/tree/main", format: "gguf" },
            { label: "Qwen3 4B", url: "https://huggingface.co/Comfy-Org/flux2-klein-4B/tree/main/split_files/text_encoders", format: "safetensors" },
            { label: "Qwen3 4B GGUF", url: "https://huggingface.co/unsloth/Qwen3-4B-GGUF/tree/main", format: "gguf" },
        ],
    },
    "flux2-klein-base-4b": {
        id: "flux2-klein-base-4b",
        family: "flux2",
        label: "Flux.2 Klein Base 4B",
        description: "Base FLUX.2 Klein 4B preset with higher CFG and standard step count.",
        defaultVramProfile: "balanced",
        runMode: "img_gen",
        paths: {},
        pathInputs: diffusionVaeLlmPathInputs,
        defaults: {
            cfgScale: 4,
            steps: 20,
            samplingMethod: "euler",
            diffusionFa: true,
            offloadToCpu: true,
        },
        supportsRefImage: true,
        downloads: [
            { label: "FLUX.2 Klein Base 4B", url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-base-4B", format: "safetensors" },
            { label: "FLUX.2 Klein Base 4B GGUF", url: "https://huggingface.co/leejet/FLUX.2-klein-base-4B-GGUF/tree/main", format: "gguf" },
            { label: "Qwen3 4B", url: "https://huggingface.co/Comfy-Org/flux2-klein-4B/tree/main/split_files/text_encoders", format: "safetensors" },
            { label: "Qwen3 4B GGUF", url: "https://huggingface.co/unsloth/Qwen3-4B-GGUF/tree/main", format: "gguf" },
        ],
    },
    "flux2-klein-9b": {
        id: "flux2-klein-9b",
        family: "flux2",
        label: "Flux.2 Klein 9B",
        description: "Fast FLUX.2 Klein 9B preset using the Qwen3 8B encoder.",
        defaultVramProfile: "balanced",
        runMode: "img_gen",
        paths: {},
        pathInputs: diffusionVaeLlmPathInputs,
        defaults: {
            cfgScale: 1,
            steps: 4,
            samplingMethod: "euler",
            diffusionFa: true,
            offloadToCpu: true,
        },
        supportsRefImage: true,
        downloads: [
            { label: "FLUX.2 Klein 9B", url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-9B", format: "safetensors" },
            { label: "FLUX.2 Klein 9B GGUF", url: "https://huggingface.co/leejet/FLUX.2-klein-9B-GGUF/tree/main", format: "gguf" },
            { label: "Qwen3 8B", url: "https://huggingface.co/Comfy-Org/flux2-klein-9B/tree/main/split_files/text_encoders", format: "safetensors" },
            { label: "Qwen3 8B GGUF", url: "https://huggingface.co/unsloth/Qwen3-8B-GGUF/tree/main", format: "gguf" },
        ],
    },
    "flux2-klein-base-9b": {
        id: "flux2-klein-base-9b",
        family: "flux2",
        label: "Flux.2 Klein Base 9B",
        description: "Base FLUX.2 Klein 9B preset with higher CFG and standard step count.",
        defaultVramProfile: "balanced",
        runMode: "img_gen",
        paths: {},
        pathInputs: diffusionVaeLlmPathInputs,
        defaults: {
            cfgScale: 4,
            steps: 20,
            samplingMethod: "euler",
            diffusionFa: true,
            offloadToCpu: true,
        },
        supportsRefImage: true,
        downloads: [
            { label: "FLUX.2 Klein Base 9B", url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-base-9B", format: "safetensors" },
            { label: "FLUX.2 Klein Base 9B GGUF", url: "https://huggingface.co/leejet/FLUX.2-klein-base-9B-GGUF/tree/main", format: "gguf" },
            { label: "Qwen3 8B", url: "https://huggingface.co/Comfy-Org/flux2-klein-9B/tree/main/split_files/text_encoders", format: "safetensors" },
            { label: "Qwen3 8B GGUF", url: "https://huggingface.co/unsloth/Qwen3-8B-GGUF/tree/main", format: "gguf" },
        ],
    },
} as const satisfies Partial<Record<string, SdModelPreset>>;
