import type { SdModelPreset } from "../types";
import {
    diffusionModelVaeT5xxlPathInputsVideo,
    diffusionModelVaeT5xxlClipVisionPathInputs,
    diffusionModelHighNoiseVaeT5xxlPathInputs,
    diffusionModelHighNoiseVaeT5xxlClipVisionPathInputs,
    diffusionModelVaeT5xxlPathInputsSmallVideo,
} from "./shared";

export const wanPresets = {
    "wan21-t2v-13b": {
        id: "wan21-t2v-13b",
        family: "wan",
        label: "Wan2.1 T2V 1.3B",
        description: "Wan2.1 text-to-video 1.3B — lightweight video generation.",
        defaultVramProfile: "low",
        runMode: "vid_gen",
        paths: {},
        pathInputs: diffusionModelVaeT5xxlPathInputsSmallVideo,
        defaults: {
            cfgScale: 6,
            samplingMethod: "euler",
            diffusionFa: true,
            videoFrames: 33,
            flowShift: 3,
        },
        downloads: [
            { label: "Wan2.1 T2V 1.3B", url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/tree/main/split_files/diffusion_models", format: "safetensors" },
            { label: "Wan2.1 VAE", url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/blob/main/split_files/vae/wan_2.1_vae.safetensors", format: "safetensors" },
            { label: "UMT5-XXL", url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/blob/main/split_files/text_encoders/umt5_xxl_fp16.safetensors", format: "safetensors" },
        ],
    },
    "wan21-t2v-14b": {
        id: "wan21-t2v-14b",
        family: "wan",
        label: "Wan2.1 T2V 14B",
        description: "Wan2.1 text-to-video 14B — high quality video generation.",
        defaultVramProfile: "low",
        runMode: "vid_gen",
        paths: {},
        pathInputs: diffusionModelVaeT5xxlPathInputsVideo,
        defaults: {
            cfgScale: 6,
            samplingMethod: "euler",
            diffusionFa: true,
            videoFrames: 33,
            flowShift: 3,
            offloadToCpu: true,
        },
        downloads: [
            { label: "Wan2.1 T2V 14B GGUF", url: "https://huggingface.co/city96/Wan2.1-T2V-14B-gguf", format: "gguf" },
            { label: "Wan2.1 VAE", url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/blob/main/split_files/vae/wan_2.1_vae.safetensors", format: "safetensors" },
            { label: "UMT5-XXL GGUF", url: "https://huggingface.co/city96/umt5-xxl-encoder-gguf", format: "gguf" },
        ],
    },
    "wan21-i2v-14b-480p": {
        id: "wan21-i2v-14b-480p",
        family: "wan",
        label: "Wan2.1 I2V 14B 480P",
        description: "Wan2.1 image-to-video 14B. Requires CLIP Vision in addition to basic paths.",
        defaultVramProfile: "low",
        runMode: "vid_gen",
        paths: {},
        pathInputs: diffusionModelVaeT5xxlClipVisionPathInputs,
        defaults: {
            cfgScale: 6,
            samplingMethod: "euler",
            diffusionFa: true,
            videoFrames: 33,
            flowShift: 3,
            offloadToCpu: true,
        },
        downloads: [
            { label: "Wan2.1 I2V 14B 480P GGUF", url: "https://huggingface.co/city96/Wan2.1-I2V-14B-480P-gguf", format: "gguf" },
            { label: "Wan2.1 VAE", url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/blob/main/split_files/vae/wan_2.1_vae.safetensors", format: "safetensors" },
            { label: "UMT5-XXL GGUF", url: "https://huggingface.co/city96/umt5-xxl-encoder-gguf", format: "gguf" },
            { label: "CLIP Vision H", url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/blob/main/split_files/clip_vision/clip_vision_h.safetensors", format: "safetensors" },
        ],
    },
    "wan22-t2v-a14b": {
        id: "wan22-t2v-a14b",
        family: "wan",
        label: "Wan2.2 T2V A14B",
        description: "Wan2.2 text-to-video with dual low-noise/high-noise diffusion models for improved quality.",
        defaultVramProfile: "low",
        runMode: "vid_gen",
        paths: {},
        pathInputs: diffusionModelHighNoiseVaeT5xxlPathInputs,
        defaults: {
            cfgScale: 3.5,
            samplingMethod: "euler",
            steps: 10,
            highNoiseCfgScale: 3.5,
            highNoiseSamplingMethod: "euler",
            highNoiseSteps: 8,
            diffusionFa: true,
            videoFrames: 33,
            flowShift: 3,
            offloadToCpu: true,
        },
        downloads: [
            { label: "Wan2.2 T2V A14B GGUF", url: "https://huggingface.co/QuantStack/Wan2.2-T2V-A14B-GGUF", format: "gguf" },
            { label: "Wan2.1 VAE", url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/blob/main/split_files/vae/wan_2.1_vae.safetensors", format: "safetensors" },
            { label: "UMT5-XXL GGUF", url: "https://huggingface.co/city96/umt5-xxl-encoder-gguf", format: "gguf" },
        ],
    },
    "wan22-i2v-a14b": {
        id: "wan22-i2v-a14b",
        family: "wan",
        label: "Wan2.2 I2V A14B",
        description: "Wan2.2 image-to-video with dual low-noise/high-noise diffusion models and CLIP Vision.",
        defaultVramProfile: "low",
        runMode: "vid_gen",
        paths: {},
        pathInputs: diffusionModelHighNoiseVaeT5xxlClipVisionPathInputs,
        defaults: {
            cfgScale: 3.5,
            samplingMethod: "euler",
            steps: 10,
            highNoiseCfgScale: 3.5,
            highNoiseSamplingMethod: "euler",
            highNoiseSteps: 8,
            diffusionFa: true,
            videoFrames: 33,
            flowShift: 3,
            offloadToCpu: true,
        },
        downloads: [
            { label: "Wan2.2 I2V A14B GGUF", url: "https://huggingface.co/QuantStack/Wan2.2-I2V-A14B-GGUF", format: "gguf" },
            { label: "Wan2.1 VAE", url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/blob/main/split_files/vae/wan_2.1_vae.safetensors", format: "safetensors" },
            { label: "UMT5-XXL GGUF", url: "https://huggingface.co/city96/umt5-xxl-encoder-gguf", format: "gguf" },
            { label: "CLIP Vision H", url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/blob/main/split_files/clip_vision/clip_vision_h.safetensors", format: "safetensors" },
        ],
    },
    "wan22-ti2v-5b": {
        id: "wan22-ti2v-5b",
        family: "wan",
        label: "Wan2.2 TI2V 5B",
        description: "Wan2.2 text-and-image-to-video 5B. Uses the smaller Wan2.2 VAE.",
        defaultVramProfile: "low",
        runMode: "vid_gen",
        paths: {},
        pathInputs: diffusionModelVaeT5xxlPathInputsVideo,
        defaults: {
            cfgScale: 6,
            samplingMethod: "euler",
            diffusionFa: true,
            videoFrames: 33,
            flowShift: 3,
            offloadToCpu: true,
        },
        downloads: [
            { label: "Wan2.2 TI2V 5B GGUF", url: "https://huggingface.co/QuantStack/Wan2.2-TI2V-5B-GGUF", format: "gguf" },
            { label: "Wan2.2 VAE", url: "https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/blob/main/split_files/vae/wan2.2_vae.safetensors", format: "safetensors" },
            { label: "UMT5-XXL GGUF", url: "https://huggingface.co/city96/umt5-xxl-encoder-gguf", format: "gguf" },
        ],
    },
} as const satisfies Partial<Record<string, SdModelPreset>>;
